dist: trusty
language: scala
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete
matrix:
  include:
    - os: linux
      jdk: openjdk-ea
    - os: linux
      jdk: openjdk11
    - os: linux
      jdk: openjdk10
    - os: linux
      jdk: openjdk9
    - os: linux
      jdk: openjdk8
    - os: linux
      jdk: oraclejdk11
#    - os: linux
#      jdk: oraclejdk10
    - os: linux
      jdk: oraclejdk9
    - os: linux
      jdk: oraclejdk8
    - os: osx
      jdk: openjdk11
    - os: osx
      jdk: openjdk10
    - os: osx
      jdk: openjdk9
    - os: osx
      jdk: openjdk8
    - os: osx
      jdk: oraclejdk9
    - os: osx
      jdk: oraclejdk8
  allow_failures:
    - jdk: openjdk-ea
scala:
  - 2.12.7
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean test
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
